Repository Samsung-Health-11/iOS, pull requests merged in 2022-05, with the labels that each got.

#4 Feature/#3
  SamsungHealth-iOS/SamsungHealth-iOS/Configuration/Resources/Assets.xcassets/ssh_icon_fitness_off.imageset/Contents.json
  SamsungHealth-iOS/SamsungHealth-iOS/Configuration/Resources/Assets.xcassets/ssh_icon_fitness_on.imageset/Contents.json
  SamsungHealth-iOS/SamsungHealth-iOS/Configuration/Resources/Assets.xcassets/ssh_icon_home_off.imageset/Contents.json
  SamsungHealth-iOS/SamsungHealth-iOS/Configuration/Resources/Assets.xcassets/ssh_icon_home_on.imageset/Contents.json
  SamsungHealth-iOS/SamsungHealth-iOS/Configuration/Resources/Assets.xcassets/ssh_icon_mypage_off.imageset/Contents.json
  SamsungHealth-iOS/SamsungHealth-iOS/Configuration/Resources/Assets.xcassets/ssh_icon_mypage_on.imageset/Contents.json
  SamsungHealth-iOS/SamsungHealth-iOS/Configuration/Resources/Assets.xcassets/ssh_icon_together_off.imageset/Contents.json
  SamsungHealth-iOS/SamsungHealth-iOS/Configuration/Resources/Assets.xcassets/ssh_icon_together_on.imageset/Contents.json
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(baby)/BabyMain.storyboard
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(baby)/BabyMainTabBarController.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(baby)/Home/BabyHome.storyboard
Labels: 영린, Feat

#6 [#5] add font style
  SamsungHealth-iOS/SamsungHealth-iOS/Helpers/AppExtensions/UIFont+.swift
Labels: 경민, Chore

#10 [#8] feat HomeView
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(baby)/Home/BabyHome.storyboard
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(baby)/Home/BabyHomeViewController.swift
Labels: 영린, Feat

#11 [#1] delete file
  SamsungHealth-iOS/SamsungHealth-iOS.xcodeproj/project.pbxproj
  SamsungHealth-iOS/SamsungHealth-iOS/Network/Base/BaseTargetType.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Network/Base/GeneralResponse.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Network/Base/MoyaLoggingPlugin.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Network/Base/NetworkBase.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(baby)/Home/Cell/BabyDummyCollectionViewCell.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(baby)/Home/Cell/BabyDummyCollectionViewCell.xib
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(baby)/Weight/Cell/BabyDummyWeightCollectionViewCell.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(baby)/Weight/Cell/BabyDummyWeightCollectionViewCell.xib
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(km)/Home/Cell/KmHomeDummyCollectionViewCell.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(km)/Home/Cell/KmHomeDummyCollectionViewCell.xib
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(km)/Weight/Cell/KmWeightDummyCollectionViewCell.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(km)/Weight/Cell/KmWeightDummyCollectionViewCell.xib
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(yi)/Home/Cell/YinHomeDummyCollectionViewCell.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(yi)/Home/Cell/YinHomeDummyCollectionViewCell.xib
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(yi)/Weight/Cell/YinWeightDummyCollectionViewCell.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(yi)/Weight/Cell/YinWeightDummyCollectionViewCell.xib
Labels: 경민, Chore

#13 [#12]chore HomeView
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(baby)/Home/BabyHome.storyboard
Labels: 영린, Chore

#15 Weight UI
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(km)/Home/KmHome.storyboard
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(km)/KmMain.storyboard
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(km)/KmMainTabBarController.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(km)/Weight/KmWeight.storyboard
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(km)/Weight/KmWeightViewController.swift
Labels: 경민, Feat

#16 그렇게 됐다
  SamsungHealth-iOS/SamsungHealth-iOS.xcodeproj/project.pbxproj
  SamsungHealth-iOS/SamsungHealth-iOS/Helpers/AppExtensions/UITextField+.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Helpers/AppExtensions/UIViewController+.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(km)/Weight/Extension/KmWeightViewController+Extension.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(km)/Weight/KmWeight.storyboard
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(km)/Weight/KmWeightViewController.swift
Labels: 경민, Feat

#18 [#7] feat WeightView
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(yi)/Weight/YinWeight.storyboard
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(yi)/Weight/YinWeightViewController.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(yi)/YinMain.storyboard
Labels: 영인, Feat

#21 [#20] pickerview 초기값
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(km)/Weight/KmWeightViewController.swift
Labels: 경민, Feat

#25 [#23] WeightView 완성
  SamsungHealth-iOS/SamsungHealth-iOS.xcodeproj/project.pbxproj
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(yi)/Weight/Extension/YinWeightViewController+Extension.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(yi)/Weight/YinWeight.storyboard
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(yi)/Weight/YinWeightViewController.swift
Labels: 영인, Chore

#24 [#14] feat WeightView
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(baby)/BabyMain.storyboard
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(baby)/Home/BabyHome.storyboard
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(baby)/Home/BabyHomeViewController.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(baby)/Weight/BabyWeight.storyboard
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(baby)/Weight/BabyWeightViewController.swift
Labels: 영린, Feat

#27 [#17] home
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(km)/Home/KmHome.storyboard
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(km)/Home/KmHomeViewController.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(km)/Weight/KmWeightViewController.swift
Labels: 경민, Feat

#28 [#19] Home UI
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(yi)/Home/YinHome.storyboard
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(yi)/Home/YinHomeViewController.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(yi)/YinMain.storyboard
Labels: 영인, Feat

#29 Feature/#17 km
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(km)/Home/KmHome.storyboard
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(km)/Home/KmHomeViewController.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(km)/Weight/KmWeightViewController.swift
Labels: 경민, Feat

#32 [#22] add network files
  SamsungHealth-iOS/SamsungHealth-iOS.xcodeproj/project.pbxproj
  SamsungHealth-iOS/SamsungHealth-iOS/Network/BabyNetwork/NetworkModel/RequestModel/BabyWaterRequestModel.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Network/BabyNetwork/NetworkModel/RequestModel/BabyWeightRequestModel.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Network/BabyNetwork/NetworkModel/ResponseModel/BabyHealthResponseModel.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Network/BabyNetwork/NetworkModel/ResponseModel/BabyWaterResponseModel.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Network/BabyNetwork/NetworkModel/ResponseModel/BabyWeightResponseModel.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Network/BabyNetwork/NetworkService/BabyHealthService.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Network/BabyNetwork/NetworkService/BabyWaterService.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Network/BabyNetwork/NetworkService/BabyWeightService.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Network/Base/NetworkConstant.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Network/Base/URLConstant.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Network/KmNetwork/NetworkModel/RequestModel/KmWaterRequestModel.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Network/KmNetwork/NetworkModel/RequestModel/KmWeightRequestModel.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Network/KmNetwork/NetworkModel/ResponseModel/KmHealthResponseModel.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Network/KmNetwork/NetworkModel/ResponseModel/KmWaterResponseModel.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Network/KmNetwork/NetworkModel/ResponseModel/KmWeightResponseModel.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Network/KmNetwork/NetworkService/KmHealthService.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Network/KmNetwork/NetworkService/KmWaterService.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Network/KmNetwork/NetworkService/KmWeightService.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Network/YinNetwork/NetworkModel/RequestModel/YinWaterRequestModel.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Network/YinNetwork/NetworkModel/RequestModel/YinWeightRequestModel.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Network/YinNetwork/NetworkModel/ResponseModel/YinHealthResponseModel.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Network/YinNetwork/NetworkModel/ResponseModel/YinWaterResponseModel.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Network/YinNetwork/NetworkModel/ResponseModel/YinWeightResponseModel.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Network/YinNetwork/NetworkService/YinHealthService.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Network/YinNetwork/NetworkService/YinWaterService.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Network/YinNetwork/NetworkService/YinWeightService.swift
Labels: 경민

#33 Feature/#31
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(baby)/Weight/BabyWeight.storyboard
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(baby)/Weight/BabyWeightViewController.swift
Labels: 영린, Feat

#35 [#34] 전체 건강 조회 서버 연걸
  SamsungHealth-iOS/SamsungHealth-iOS/Network/BabyNetwork/NetworkModel/RequestModel/BabyWaterRequestModel.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Network/BabyNetwork/NetworkModel/RequestModel/BabyWeightRequestModel.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Network/BabyNetwork/NetworkModel/ResponseModel/BabyHealthResponseModel.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Network/BabyNetwork/NetworkModel/ResponseModel/BabyWaterResponseModel.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Network/BabyNetwork/NetworkModel/ResponseModel/BabyWeightResponseModel.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Network/BabyNetwork/NetworkService/BabyHealthService.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Network/Base/URLConstant.swift
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(baby)/Home/BabyHome.storyboard
  SamsungHealth-iOS/SamsungHealth-iOS/Scene(baby)/Home/BabyHomeViewController.swift
Labels: 영린, Feat
